### ISSUE TITLE
Distance-vector protocols: Duplicate rule numbering for Rule 3

### ISSUE THREAD

**Issue by laurenmchin** [berkeley-cs168/textbook#6]
I noticed a small issue — two rules are numbered as **Rule 3** ([Rule 3 #1](https://textbook.cs168.io/routing/distance-vector.html#rule-3-resending), [Rule 3 #2](https://textbook.cs168.io/routing/distance-vector.html#rule-3-expiring)). This may cause confusion for readers, could you update the numbering for Rule 3 onwards?

**Comment by peyrin** [comment]
This was intentional ([see the slides, which have a rule titled "Resending and Expiring"](https://docs.google.com/presentation/d/1hFkNpuSk8NABN-awJq2VKUNvm1IYBZC7l52v_TW7054/edit#slide=id.g2ed56a414bf_0_1177)), but I might consider changing this for next semester.

**Comment by laurenmchin** [comment]
Thanks so much for the clarification! I appreciate the insight. If it’s helpful, maybe using 3A and 3B could be an option for future clarity, but totally understand if you’d prefer to keep it as is.

**Comment by peyrin** [comment]
I don't think I'd use 3A and 3B - using 5A and 5B for split horizon and poison reverse was an intentional choice, to show that you choose either 5A or 5B (but not both). Will think about this some more before next semester though.
