### ISSUE TITLE
Potentially Incorrect Number of Fixed Bits

### ISSUE THREAD

**Issue by BlueFlame202** [berkeley-cs168/textbook#8]
Link: https://arc.net/l/quote/naktevto

I think along the same line as another post on Ed, I think the number of fixed bits in this screenshot need to be corrected:
<img width="919" alt="Screenshot 2024-10-13 at 11 57 50 PM" src="https://github.com/user-attachments/assets/eab17cae-01f0-46e2-bf44-a15c08cc8875">

so I think the first two should be 192.0.0.0/8 and 192.0.0.0/12 and the later two are 192.0.0.0/4 and 200.0.0.0/5. After this change I think the next line about it not being clear at a first glance that the second is a subset of the first might not actually be true since it is much more clear that the second is a subset of the first since 5 > 4.

**Comment by peyrin** [comment]
Fixed via https://github.com/berkeley-cs168/textbook/commit/74d4701b232e62b7eaf8d7f99e9b0f29a0026062
